//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MayTheFourth.Utils.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MayTheFourth.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string BirthYearIsRequired {
            get {
                return ResourceManager.GetString("BirthYearIsRequired", resourceCulture);
            }
        }
        
        public static string CargoCapacityIsRequired {
            get {
                return ResourceManager.GetString("CargoCapacityIsRequired", resourceCulture);
            }
        }
        
        public static string ClassIsRequired {
            get {
                return ResourceManager.GetString("ClassIsRequired", resourceCulture);
            }
        }
        
        public static string ClimateIsRequired {
            get {
                return ResourceManager.GetString("ClimateIsRequired", resourceCulture);
            }
        }
        
        public static string ConsumablesIsRequired {
            get {
                return ResourceManager.GetString("ConsumablesIsRequired", resourceCulture);
            }
        }
        
        public static string CostInCreditsIsRequired {
            get {
                return ResourceManager.GetString("CostInCreditsIsRequired", resourceCulture);
            }
        }
        
        public static string CrewIsRequired {
            get {
                return ResourceManager.GetString("CrewIsRequired", resourceCulture);
            }
        }
        
        public static string DiameterIsRequired {
            get {
                return ResourceManager.GetString("DiameterIsRequired", resourceCulture);
            }
        }
        
        public static string DirectorIsRequired {
            get {
                return ResourceManager.GetString("DirectorIsRequired", resourceCulture);
            }
        }
        
        public static string EpisodeIsRequired {
            get {
                return ResourceManager.GetString("EpisodeIsRequired", resourceCulture);
            }
        }
        
        public static string EyeColorIsRequired {
            get {
                return ResourceManager.GetString("EyeColorIsRequired", resourceCulture);
            }
        }
        
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        public static string GenderIsRequired {
            get {
                return ResourceManager.GetString("GenderIsRequired", resourceCulture);
            }
        }
        
        public static string GravityIsRequired {
            get {
                return ResourceManager.GetString("GravityIsRequired", resourceCulture);
            }
        }
        
        public static string HairColorIsRequired {
            get {
                return ResourceManager.GetString("HairColorIsRequired", resourceCulture);
            }
        }
        
        public static string HeightIsRequired {
            get {
                return ResourceManager.GetString("HeightIsRequired", resourceCulture);
            }
        }
        
        public static string HyperdriveRatingIsRequired {
            get {
                return ResourceManager.GetString("HyperdriveRatingIsRequired", resourceCulture);
            }
        }
        
        public static string InvalidConversion {
            get {
                return ResourceManager.GetString("InvalidConversion", resourceCulture);
            }
        }
        
        public static string LengthIsRequired {
            get {
                return ResourceManager.GetString("LengthIsRequired", resourceCulture);
            }
        }
        
        public static string ManufacturerIsRequired {
            get {
                return ResourceManager.GetString("ManufacturerIsRequired", resourceCulture);
            }
        }
        
        public static string MaxSpeedIsRequired {
            get {
                return ResourceManager.GetString("MaxSpeedIsRequired", resourceCulture);
            }
        }
        
        public static string MGLTIsRequired {
            get {
                return ResourceManager.GetString("MGLTIsRequired", resourceCulture);
            }
        }
        
        public static string ModelIsRequired {
            get {
                return ResourceManager.GetString("ModelIsRequired", resourceCulture);
            }
        }
        
        public static string NameIsRequired {
            get {
                return ResourceManager.GetString("NameIsRequired", resourceCulture);
            }
        }
        
        public static string OpeningCrawlIsRequired {
            get {
                return ResourceManager.GetString("OpeningCrawlIsRequired", resourceCulture);
            }
        }
        
        public static string OrbitalPeriodIsRequired {
            get {
                return ResourceManager.GetString("OrbitalPeriodIsRequired", resourceCulture);
            }
        }
        
        public static string PassengersIsRequired {
            get {
                return ResourceManager.GetString("PassengersIsRequired", resourceCulture);
            }
        }
        
        public static string PlanetIdIsRequired {
            get {
                return ResourceManager.GetString("PlanetIdIsRequired", resourceCulture);
            }
        }
        
        public static string PopulationIsRequired {
            get {
                return ResourceManager.GetString("PopulationIsRequired", resourceCulture);
            }
        }
        
        public static string ProducerIsRequired {
            get {
                return ResourceManager.GetString("ProducerIsRequired", resourceCulture);
            }
        }
        
        public static string RegisterNotFound {
            get {
                return ResourceManager.GetString("RegisterNotFound", resourceCulture);
            }
        }
        
        public static string ReleaseDateIsRequired {
            get {
                return ResourceManager.GetString("ReleaseDateIsRequired", resourceCulture);
            }
        }
        
        public static string RotationPeriodIsRequired {
            get {
                return ResourceManager.GetString("RotationPeriodIsRequired", resourceCulture);
            }
        }
        
        public static string SkinColorIsRequired {
            get {
                return ResourceManager.GetString("SkinColorIsRequired", resourceCulture);
            }
        }
        
        public static string SqlFileCantBeExecuted {
            get {
                return ResourceManager.GetString("SqlFileCantBeExecuted", resourceCulture);
            }
        }
        
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        public static string SurfaceWaterIsRequired {
            get {
                return ResourceManager.GetString("SurfaceWaterIsRequired", resourceCulture);
            }
        }
        
        public static string TerrainIsRequired {
            get {
                return ResourceManager.GetString("TerrainIsRequired", resourceCulture);
            }
        }
        
        public static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        public static string WeightIsRequired {
            get {
                return ResourceManager.GetString("WeightIsRequired", resourceCulture);
            }
        }
        
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
    }
}
