version: '3.5'
services: 
  db_maythefourth:
    image: postgres:15.4-alpine3.18
    hostname: db_maythefourth
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: maythefourth
    ports:
      - "5432:5432"
    expose:
      - "5432"
    deploy:
      resources: 
        limits:
          cpus: "0.5"
          memory: "1GB"
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./scripts/postgres/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 15s
      timeout: 25s
    command:
      [
        "postgres",
        "-c",
        "config_file=/docker-entrypoint-initdb.d/postgresql.conf",
      ]

volumes:
  postgres-db:

networks:
  default:
    driver: bridge
    name: maythefourth