name: Build, tests and deploy

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['main']


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./src/MayTheFourth

    steps:  
      - uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Display dotnet version
        run: dotnet --version

      - name: Installing EF Tools
        run: dotnet tool install --global dotnet-ef

      - name: Installing dependencies
        run: dotnet restore
      
      - name: Building
        run: dotnet build --configuration Release
      
      - name: Testing
        run: dotnet test


